# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Pred <- function(X, U, predict_t, phi, p, psi, q, tau, S, r) {
    .Call(`_BSD_Pred`, X, U, predict_t, phi, p, psi, q, tau, S, r)
}

fit <- function(X, U, beta, p, q, S, r) {
    .Call(`_BSD_fit`, X, U, beta, p, q, S, r)
}

grad <- function(X, U, beta, p, q, S, r) {
    .Call(`_BSD_grad`, X, U, beta, p, q, S, r)
}

likeli <- function(X, U, phi, p, psi, q, tau, S, r, sigma) {
    .Call(`_BSD_likeli`, X, U, phi, p, psi, q, tau, S, r, sigma)
}

